version: "3.9"

services:
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: scripts/docker-entrypoint.sh
    env_file: .env
    ports:
      - '3001:3001'

  postgres:
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "$POSTGRES_DATABASE"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s
    image: postgres:15.3-alpine
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db: